![imagen](./img/ejercicios.png)

# INFORMACIÓN DEL PROYECTO

### TÍTULO

# Un Enfoque Data-Driven sobre el Sello "Bio" en Alimentos: Auditoría de Nutrientes, Grado de Procesamiento e Impacto Ambiental

### TEMA

Este proyecto audita la calidad real de los alimentos procesados mediante el cruce de Open Food Facts y datos macroeconómicos de la FAO. El objetivo es contrastar el marketing nutricional con la evidencia científica y la influencia de la producción agraria nacional en la química de los productos.

Ejes del Análisis:

1. El Fenómeno Bio y Plant-Based: Validación de si las etiquetas orgánicas y vegetales realmente ofrecen un mejor perfil nutricional o si esconden un mayor ultraprocesamiento (NOVA) y exceso de sodio.

2. Marcas Blancas vs. Multinacionales: Comparativa de calidad nutricional en productos de conveniencia según el tipo de corporación.

3. Impacto Regulatorio y Fiscal: Evaluación de la eficacia del impuesto al azúcar en el Reino Unido frente a los mercados de España y Francia.

4. Auditoría del Nutri-Score: Análisis de las limitaciones del algoritmo frente a productos con baja densidad calórica pero alta manipulación industrial.

5. Soberanía Alimentaria (Cruce FAO): Estudio de cómo la disponibilidad local de materias primas (aceites, cereales y proteínas) determina la formulación y calidad de las grasas y fibras en el lineal de cada país.

### HIPÓTESIS

#### 1. Los productos con etiqueta 'Bio/Organic' no tienen un mejor perfil nutricional que sus equivalentes convencionales

#### 2. Los productos con etiqueta 'Bio/Organic' son más procesados y tienen mayor impacto ambiental que sus equivalentes convencionales

#### 3. Las marcas blancas tienen un perfil nutricional significativamente mejor que las grandes multinacionales en categorías de conveniencia (Ready-to-eat)

#### 4. Los productos de la categoria "Plant-based alternatives" tienen peor perfil nutricional y más sal que los productos cárnicos naturales debido a la necesidad de mejorar su palatabilidad

#### 5. El impuesto del azucar de Reino Unido funciona, resultando en menor contenido de azucar que España y Francia en las categorias "bebidas" y "snacks"

#### 6. España tiene menor ratio de grasas saturadas que el resto de paises debido al uso de aceites vegetales locales

#### 7. El Nutri-Score es un algoritmo cuestionable que premia la baja densidad calórica, pero no penaliza el procesamiento industrial

### Bonus cruzando con datos de producción/importación de la FAO

#### 8. Los países con mayor producción de aceites vegetales insaturados tienen productos procesados con un ratio de grasas saturadas notablemente inferior al de países importadores de aceite de palma

#### 9. Los países con mayor producción de proteína animal tienen alternativas vegetales más procesadas al intentar imitar texturas cárnicas complejas

#### 10. Los países con mayor producción de avena presentan una categoría "cereal_bread" con mayor contenido en fibra debido a la disponibilidad local y menor precio que el trigo o el maíz.

## OBTENCIÓN DE LOS DATOS

### DATASETS Y FUENTES ALTERNATIVAS DE DATOS

Incluye aquí una vista del dataset o datasets de los que partirás para poder evaluar tu hipótesis. <br>
También incluye el origen de estos datos y su fuente.

In [ ]:
import pandas as pd

# Este es el dataset principal donde hay cerca de 10.000 alimentos, con sus correspondientes marcas, países de comercialización, perfil nutricional etc.
food = pd.read_csv('/home/mikel/.cache/kagglehub/datasets/kanchana1990/global-food-nutrition-database10k-products/versions/1/openfoodfacts_nutrition_final_2025-12-10.csv')

In [ ]:
# Este pequeño dataset es para correlacionar la importación de aceite de palma por país con la cantidad de snacks que se comercializan que contienen este aceite
palm_oil_import = pd.read_csv('FAOSTAT_aceite_palma_importado.csv')

In [ ]:
# Este otro dataset es para correlacionar producción de cereales con productos derivados de estos, comparar producción de carne con sus imitaciones veganas, y la leche con sus alternativas vegetales
primary_stock_production = pd.read_csv('FAOSTAT_cereales,aceites,leche-producidas.csv')

Muestra mediante un head() los principales datasets con los que vas a trabajar

In [7]:
food.head()

,code,product_name,brands,countries,quantity,categories,labels,nutriscore_grade,ecoscore_grade,nova_group,ingredients_text,energy-kcal_100g,fat_100g,saturated-fat_100g,carbohydrates_100g,sugars_100g,fiber_100g,proteins_100g,salt_100g,sodium_100g
0,6111035000430,Sidi Ali,سيدي علي,Morocco,33 cl,"Beverages and beverages preparations,Beverages...",NaN,a,not-applicable,NaN,OBD1 999 999 1112606 266963207 mb,0.0,0.0,0.0,4.2,1.4,0.0,0.0,0.000000,0.000000
1,6111242100992,perly,perly,"Morocco,United States",100 g,"Dairies,Fermented foods,Fermented milk product...",NaN,unknown,b,3.0,"milk cream, cream, sugar, banana, bacteria",97.0,3.0,NaN,9.4,NaN,NaN,8.0,NaN,NaN
2,6111035002175,Sidi Ali,Sidi Ali,Morocco,2 L,"Beverages and beverages preparations,Beverages...",Green Dot,a,not-applicable,1.0,"Sodium, Calcium, Magnésium, Potassium, Bicarbo...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000
3,6111035000058,Eau minérale naturelle,"Les Eaux Minérales d'oulmès,Sidi Ali",Morocco,"1,5 L","Beverages and beverages preparations,Beverages...","ISO 22000,ISO 14001,ISO 45001,ISO 9001",a,not-applicable,1.0,100% mineral water,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.065000,0.026000
4,6111252421568,اكوافينا,AQUAFINA,المغرب,33cl,"Boissons et préparations de boissons,Boissons,...",NaN,a,not-applicable,NaN,ouverture et avant le : Voir bouteille. après ...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000508,0.000203

In [8]:
palm_oil_import.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,TCL,Crops and livestock products,250,France,5610,Import quantity,2165,Palm oil,2020,2020,t,422456.94,A,Official figure,NaN
1,TCL,Crops and livestock products,250,France,5610,Import quantity,2165,Palm oil,2021,2021,t,289008.09,A,Official figure,NaN
2,TCL,Crops and livestock products,250,France,5610,Import quantity,2165,Palm oil,2022,2022,t,239777.55,A,Official figure,NaN
3,TCL,Crops and livestock products,250,France,5610,Import quantity,2165,Palm oil,2023,2023,t,153021.70,A,Official figure,NaN
4,TCL,Crops and livestock products,250,France,5610,Import quantity,2165,Palm oil,2024,2024,t,143049.33,A,Official figure,NaN

In [9]:
primary_stock_production.head()

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code (CPC),Item,Year Code,Year,Unit,Value,Flag,Flag Description,Note
0,QCL,Crops and livestock products,250,France,5510,Production,0115,Barley,2020,2020,t,10277230.0,A,Official figure,NaN
1,QCL,Crops and livestock products,250,France,5510,Production,0115,Barley,2021,2021,t,11321320.0,A,Official figure,NaN
2,QCL,Crops and livestock products,250,France,5510,Production,0115,Barley,2022,2022,t,11285440.0,A,Official figure,NaN
3,QCL,Crops and livestock products,250,France,5510,Production,0115,Barley,2023,2023,t,12143490.0,A,Official figure,NaN
4,QCL,Crops and livestock products,250,France,5510,Production,0115,Barley,2024,2024,t,9669250.0,A,Official figure,NaN